#!/usr/bin/env ruby

KBD = File.open("/dev/tty", "r")

print "Source says: "
src = `grep VERSION.= lib/runecms/version.rb`
ver = src.split.last[1..-2]
puts ver
puts

print "Install says: "
system("rcms version")
puts

print "Continue? (Yn)  "
resp = KBD.gets.chomp

if resp == "y" || resp == "Y" || resp.empty?
  puts "Continuing...\n "   # all OK
else
  abort "\nExiting\n "
end

update = <<-EOF
  gem build runecms.gemspec && 
  gem push runecms-*.gem && 
  gem uninstall -x runecms && 
  gem install runecms
EOF

system(update)

